import type { AnimeData } from "./types"

export const mockAnimeData: AnimeData[] = [
  {
    id: "1",
    title: "Demon Slayer: Kimetsu no Yaiba",
    coverImage: "/demon-slayer-inspired-poster.png",
    synopsis:
      "A boy raised by boars, who wears a boar's head, boards the Infinity Train on a new mission with the Flame Pillar along with another boy who reveals his true power when he sleeps.",
    releaseDate: "2023-04-15",
    episodeCount: 12,
    rating: 9.2,
    genres: ["Action", "Fantasy", "Adventure"],
  },
  {
    id: "2",
    title: "Attack on Titan: Final Season",
    coverImage: "/titans-clash.png",
    synopsis:
      "The war for Paradis zeroes in on Shiganshina just as Jaegerists have seized control. After taking a huge blow from a surprise attack led by Eren, Marley swiftly acts to return the favor.",
    releaseDate: "2023-03-10",
    episodeCount: 16,
    rating: 9.5,
    genres: ["Action", "Drama", "Fantasy"],
  },
  {
    id: "3",
    title: "Jujutsu Kaisen",
    coverImage: "/cursed-energy-clash.png",
    synopsis:
      "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman school to be able to locate the demon's other body parts and thus exorcise himself.",
    releaseDate: "2023-02-20",
    episodeCount: 24,
    rating: 8.8,
    genres: ["Action", "Supernatural"],
  },
  {
    id: "4",
    title: "My Hero Academia",
    coverImage: "/heroes-united.png",
    synopsis:
      "A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.",
    releaseDate: "2023-02-05",
    episodeCount: 25,
    rating: 8.5,
    genres: ["Action", "Comedy", "Superhero"],
  },
  {
    id: "5",
    title: "Chainsaw Man",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime chainsaw man poster",
    synopsis:
      "Following a betrayal, a young man left for dead is reborn as a powerful devil-human hybrid after merging with his pet devil and is soon enlisted into an organization dedicated to hunting devils.",
    releaseDate: "2022-10-12",
    episodeCount: 12,
    rating: 8.9,
    genres: ["Action", "Horror", "Supernatural"],
  },
  {
    id: "6",
    title: "Spy x Family",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime spy family poster",
    synopsis:
      "A spy on an undercover mission gets married and adopts a child as part of his cover. His wife and daughter have secrets of their own, and all three must strive to keep together.",
    releaseDate: "2022-09-18",
    episodeCount: 25,
    rating: 8.7,
    genres: ["Action", "Comedy", "Slice of Life"],
  },
  {
    id: "7",
    title: "One Piece",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime one piece poster",
    synopsis:
      "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger. The famous mystery treasure named 'One Piece'.",
    releaseDate: "2022-08-07",
    episodeCount: 1000,
    rating: 8.9,
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: "8",
    title: "Violet Evergarden",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime violet evergarden poster",
    synopsis:
      "In the aftermath of a great war, Violet Evergarden, a young female ex-soldier, gets a job at a writers' agency and goes on assignments to create letters that can connect people.",
    releaseDate: "2022-07-22",
    episodeCount: 13,
    rating: 8.9,
    genres: ["Drama", "Fantasy", "Slice of Life"],
  },
  {
    id: "9",
    title: "Fullmetal Alchemist: Brotherhood",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime fullmetal alchemist brotherhood poster",
    synopsis:
      "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes wrong and leaves them in damaged physical forms.",
    releaseDate: "2022-06-15",
    episodeCount: 64,
    rating: 9.1,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: "10",
    title: "Death Note",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime death note poster",
    synopsis:
      "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
    releaseDate: "2022-05-03",
    episodeCount: 37,
    rating: 9.0,
    genres: ["Mystery", "Psychological", "Supernatural"],
  },
  {
    id: "11",
    title: "Your Name",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime your name poster",
    synopsis:
      "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    releaseDate: "2021-12-10",
    episodeCount: 1,
    rating: 8.8,
    genres: ["Drama", "Romance", "Supernatural"],
  },
  {
    id: "12",
    title: "Haikyuu!!",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime haikyuu poster",
    synopsis:
      "Determined to be like the volleyball championship's star player Shouyou, a short boy nicknamed 'the small giant,' joins his school's volleyball club.",
    releaseDate: "2021-11-05",
    episodeCount: 85,
    rating: 8.7,
    genres: ["Comedy", "Drama", "Sports"],
  },
  {
    id: "13",
    title: "Hunter x Hunter",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime hunter x hunter poster",
    synopsis:
      "Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks for his father who left him when he was younger.",
    releaseDate: "2021-10-20",
    episodeCount: 148,
    rating: 9.0,
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: "14",
    title: "Steins;Gate",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime steins gate poster",
    synopsis:
      "A group of friends create a device that can send messages to the past, but their actions have unforeseen consequences.",
    releaseDate: "2021-09-15",
    episodeCount: 24,
    rating: 9.1,
    genres: ["Sci-Fi", "Thriller"],
  },
  {
    id: "15",
    title: "Naruto: Shippuden",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime naruto shippuden poster",
    synopsis:
      "Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninja in the village.",
    releaseDate: "2021-08-01",
    episodeCount: 500,
    rating: 8.6,
    genres: ["Action", "Adventure", "Comedy"],
  },
  {
    id: "16",
    title: "Made in Abyss",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime made in abyss poster",
    synopsis: "A girl and her robot companion descend into the depths of a giant pit in search of her mother.",
    releaseDate: "2020-12-20",
    episodeCount: 13,
    rating: 8.8,
    genres: ["Adventure", "Mystery", "Sci-Fi"],
  },
  {
    id: "17",
    title: "Cowboy Bebop",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime cowboy bebop poster",
    synopsis: "The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners.",
    releaseDate: "2020-11-15",
    episodeCount: 26,
    rating: 8.9,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: "18",
    title: "Neon Genesis Evangelion",
    coverImage: "/placeholder.svg?height=450&width=300&query=anime neon genesis evangelion poster",
    synopsis: "A teenage boy finds himself recruited as a member of an elite team of pilots by his father.",
    releaseDate: "2020-10-04",
    episodeCount: 26,
    rating: 8.5,
    genres: ["Action", "Drama", "Mecha"],
  },
]
